---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: darkweb-recrawler-deployment
  labels:
    app: darkweb-recrawler
    tier: recrawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: darkweb-recrawler
      tier: recrawler
  template:
    metadata:
      labels:
        app: darkweb-recrawler
        tier: recrawler
    spec:
      containers:
        - name: darkweb-recrawler
          image: "{{ .Values.darkweb.image.name }}:{{ .Values.darkweb.image.tag }}"
          imagePullPolicy: Always
          volumeMounts:
            - name: darkweb-recrawler
              mountPath: /mnt/data
          {{- if .Values.elasticsearch_ip }}
          env:
            - name: elasticsearchIP
              value: {{ .Values.elasticsearch_ip }}
          {{- end }}
      volumes:
        - name: darkweb-recrawler
          persistentVolumeClaim:
            claimName: darkweb-recrawler-pv-claim
