kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: darkweb-recrawler-pv-claim
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi